---
cache:
  directories:
    - "$(npm config get prefix)/bin"

language: python
python: '2.7'

install:
  - nvm install stable
  - nvm use stable
  - npm install -g textlint textlint-plugin-markdown textlint-rule-no-todo textlint-rule-no-empty-section
    textlint-rule-common-misspellings textlint-rule-alex textlint-rule-rousseau

script:
  - find . -name '*.md' -print | xargs -n1 textlint -c .textlintrc.js -f pretty-error

notifications:
  email: false
