---
cache:
  directories:
    - "$(npm config get prefix)/bin"

language: python
python: '2.7'

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

matrix:
  fast_finish: true

env:
  - TEST_RUN="tests/textlint-test.sh"
  - TEST_RUN="tests/shellcheck-test.sh"
  - TEST_RUN="tests/signed-off-by-test.sh"

install:
  - nvm install stable
  - nvm use stable
  - npm install -g textlint textlint-rule-alex textlint-rule-common-misspellings
    textlint-rule-no-dead-link textlint-rule-no-empty-section
    textlint-rule-rousseau textlint-rule-no-todo

script: "$TEST_RUN"

notifications:
  email: false
